title: Bogueur
subtitle: "Contient du PHP avec Symfony ou Silex, un peu de Javascript avec jQuery...<br> Enfin que du bonheur!"
description: "Contient du PHP avec Symfony ou Silex, un peu de Javascript avec jQuery"
url: "http://localhost/projets/bogueur/dev/output_dev"
twitter: pimwib
github: pimwib
atom: false
disqus: bogueur
assets_version: 1.1
